### PR TITLE
Fix Journal image problems (filenames and macOS shadow)

### PR DESCRIPTION
**Pull request by popkirby**
For some languages, images did not rendered correctly, so I fixed them.

- ES/t8.png was not transparent
- Fix directory name for "PT_BR", "ZH_CN"
- Lower some images' filename for case sensitive filesystems

Additionally, drop shadow of initial image remains regardless of what image is shown. So I disabled drop shadow in Journal app.

### CODE REVIEW

**Comment by KockaAdmiralac** [comment]
Directory names were changed in #21, I think we should try to merge/implement these changes there

**Comment by popkirby** [comment]
I can rebase this repository for `journal-update` branch and change the destination of this pr to it.

**Comment by vinyldarkscratch** [comment]
Please do, @popkirby, and thank you for your help on this!  :smile:

**Comment by popkirby** [comment]
Rebase completed! 🎉  @vinyldarkscratch 
I found that `ES/c1.png` is missing, so I add it too.

**Comment by vinyldarkscratch** [comment]
Thank you, @popkirby!  Will review once I'm back from my internship.  :wink:

**Comment by vinyldarkscratch** [comment]
Thanks for the PR, @popkirby!

**Pull request merged**
